app = "di-fernandes-shop"
primary_region = "gru"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[build]
  dockerfile = "Dockerfile"

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 50

  # HTTP (80) e HTTPS (443)
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  # Healthchecks (bate no /healthz do seu server)
  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
    method = "get"
    path = "/healthz"
